"""empty message

Revision ID: 27f64f0b447a
Revises: a0f9efcd0bb1
Create Date: 2025-03-25 12:22:39.673030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f64f0b447a'
down_revision = 'a0f9efcd0bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('s_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('m_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('l_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('l_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('m_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('s_size',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
